########## How To Use Docker Image ###############
##
##  Image Name: denny/shellcheck:1.0
##  Git link: https://github.com/DennyZhang/devops_docker_image/blob/tag_v5/codecheck/Dockerfile_shellcheck_1_0
##  Docker hub link:
##  Build docker image: docker build --no-cache -f Dockerfile_shellcheck_1_0 -t denny/shellcheck:1.0 --rm=true .
##  How to use
##      docker run -t -d --privileged -v ${code_dir}:/code --name shellcheck --entrypoint=/bin/bash denny/shellcheck:1.0
##      docker exec -it shellcheck python /enforce_shellcheck.py --code_dir /code --check_ignore_file /.shellcheck_ignore
##  Description: https://www.dennyzhang.com/shellcheck
##
##  Read more: https://www.dennyzhang.com/docker_code_check
##################################################
# Base Docker image: https://hub.docker.com/r/koalaman/shellcheck/tags/

FROM koalaman/shellcheck:v0.4.6

LABEL maintainer "Denny<https://www.dennyzhang.com/contact>"

user root

WORKDIR /

ADD https://raw.githubusercontent.com/DennyZhang/devops_public/tag_v7/python/enforce_shellcheck/enforce_shellcheck.py /enforce_shellcheck.py

RUN chmod o+x /*.py && apk add --update python

ENTRYPOINT ["/bin/sh"]
